name: Build Snap for ARMHF

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # QEMU installieren, damit ARM-Programme laufen können
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm

      # Snapcraft installieren
      - name: Install Snapcraft
        run: sudo snap install snapcraft --classic

      # Snap für ARMHF bauen
      - name: Build snap (armhf)
        run: |
          snapcraft --destructive-mode --target-arch=armhf

      # Artefakt hochladen (.snap-Datei)
      - name: Upload Snap artifact
        uses: actions/upload-artifact@v4
        with:
          name: hello-rcu-snap
          path: ./*.snap

